name: Deployment

on:
  push:
    branches: main

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        REPO: github.com/xjcwliucy/xjcwliucy.github.io
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name "RainBot"
        git config --global user.email "RainBot@local.host"
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:gh-pages